services:
  privoxy:
    #image: ajoergensen/privoxy:latest
    image: intrepidde/rpi-privoxy:latest
    container_name: privoxy
    ports:
      - "8118:8118"
    environment:
      TZ: Europe/Paris
    sysctls:
      ## Recommended if using ipv4 only
      - net.ipv6.conf.all.disable_ipv6=1
    volumes:
      - ./config:/etc/privoxy
      - ./script:/etc/privoxy/script
    restart: always
