networks:
  Jötunheim_nw:
    driver: bridge
services:
  openldap:
    container_name: Yggdrasil
    image: bitnami/openldap:latest
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=$ADMIN_USERNAME
      - LDAP_ADMIN_PASSWORD=$ADMIN_PASSWORD
      - LDAP_USERS=$USERS
      - LDAP_PASSWORDS=$PASSWORDS
      - LDAP_ROOT=$DN_ROOT
#      - LDAP_ADMIN_DN=$ADMIN_DN

    networks:
      - Jötunheim_nw
    volumes:
      - 'openldap_data:/bitnami/openldap'
#  myapp:
#    image: 'YOUR_APPLICATION_IMAGE'
#    networks:
#      - my-network
volumes:
  openldap_data:
    driver: local
