services:
  adguardhome:
    image: adguard/adguardhome
    container_name: Heimdall
#    network_mode: "host"
    ports:
      - "192.168.1.74:53:53/tcp"
      - "192.168.1.74:53:53/udp"
      - "784:784/udp"
      - "853:853/tcp"
      - "3000:3000/tcp"
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - ./workdir:/opt/adguardhome/work
      - ./confdir:/opt/adguardhome/conf
    restart: always
