#version: '3'
services:
  portainer:
    image: portainer/portainer-ee:latest
    ports:
      - 9443:9443
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
#      - portainer_data:/data
      - ./data:/data
    restart: always
    container_name: Folkvangr
#volumes:
#  portainer_data:
